spring:
  application:
    name: spring-cloud-vault-demo

  config:
    import: vault://

  cloud:
    vault:
      host: vault.default.svc.cluster.local
      port: 8200
      scheme: http
      authentication: kubernetes
      kubernetes:
        role: demo-app-role
      kv:
        enabled: true
        backend: kvv2
        application-name: demo-app/creds
#        default-context: credentials


#  spring.cloud.vault.kubernetes.service-account-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token
#  spring.cloud.vault.kubernetes.service-account-ca-cert-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt

logging:
  level:
    org.springframework.cloud.vault: DEBUG
