apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: app
  labels:
    app: demo-app
spec:
  replicas: 1 # Modify based on your requirements
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      serviceAccountName: demo-app-service-account
      containers:
        - name: demo-app-container
          image: docker.io/library/demo-app:v2.7
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.25"
            limits:
              memory: "1Gi"
              cpu: "0.5"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5